// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/SubGame/LudoQuick.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LudoQuick {

  /// <summary>Holder for reflection information generated from Proto/SubGame/LudoQuick.proto</summary>
  public static partial class LudoQuickReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/SubGame/LudoQuick.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LudoQuickReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1Qcm90by9TdWJHYW1lL0x1ZG9RdWljay5wcm90bxIJTHVkb1F1aWNrIjwK",
            "CVJvdXRlSW5mbxIQCghjaGVzc19pZBgBIAEoBRIQCghnb2xkX2JhZxgCIAEo",
            "BRILCgNwb3MYAyABKAUiYgoIVXNlckluZm8SEAoIY2hhaXJfaWQYASABKAUS",
            "KAoKcm91dGVfaW5mbxgCIAMoCzIULkx1ZG9RdWljay5Sb3V0ZUluZm8SGgoS",
            "ZmluaXNoX2xpbmVfc3dpdGNoGAMgASgIIsEBCglDaGVzc0dyaWQSDgoGcG9z",
            "X2lkGAEgASgFEhIKCnNhZmVfaG91c2UYAiABKAUSEAoIZ29sZF9iYWcYAyAB",
            "KAUSDAoEcHJvcBgEIAEoBRIOCgZzd2l0Y2gYBSABKAUSEgoKaW5mbGVjdGlv",
            "bhgGIAEoBRIRCgluZXh0X3BvczEYByABKAUSEQoJbmV4dF9wb3MyGAggASgF",
            "EhMKC3N0YXJ0X3BvaW50GAkgASgFEhEKCWVuZF9wb2ludBgKIAEoBSJmChBN",
            "c2dTY2VuZUluZm9SZXNwEhIKCmdhbWVfc3RhdGUYASABKAUSFgoOdGltZV9y",
            "ZW1haW5pbmcYAiABKAUSJgoJdXNlcl9pbmZvGAMgAygLMhMuTHVkb1F1aWNr",
            "LlVzZXJJbmZvIjMKEE1zZ1N0YXJ0RGljZVJlc3ASEAoIY2hhaXJfaWQYASAB",
            "KAUSDQoFdGltZXMYAiABKAUiNwoQTXNnVGhyb3dEaWNlUmVzcBIQCghjaGFp",
            "cl9pZBgBIAEoBRIRCglkaWNlX3JvbGwYAiABKAUiNQoPTXNnT3BlcmF0ZVJv",
            "dXRlEhAKCGNoYWlyX2lkGAEgASgFEhAKCGNoZXNzX2lkGAIgASgFImcKD01z",
            "Z0RpY2VJbmZvUmVzcBIQCghjaGFpcl9pZBgBIAEoBRIQCghjaGVzc19pZBgC",
            "IAEoBRIRCglyb3V0ZV9udW0YAyABKAUSDwoHcHJvcF9pZBgEIAEoBRIMCgRj",
            "b2RlGAUgASgFInMKCkdhbWVSZXN1bHQSEAoIY2hhaXJfaWQYASABKAUSJgoJ",
            "dXNlcl9pbmZvGAIgASgLMhMuTHVkb1F1aWNrLlVzZXJJbmZvEhEKCXVzZXJf",
            "Z29sZBgDIAEoAxILCgN3aW4YBCABKAMSCwoDYmV0GAUgASgDIjYKDU1zZ1Jl",
            "c3VsdFJlc3ASJQoGcmVzdWx0GAEgAygLMhUuTHVkb1F1aWNrLkdhbWVSZXN1",
            "bHQqyAEKD0VNc2dJREx1ZG9RdWljaxIWChJNc2dJRF9GaXJzdFB1Ymxpc2gQ",
            "ABIXChNTVUJfU0NfRmlyc3RQdWJsaXNoEAESFAoQU1VCX1NDX1N0YXJ0RGlj",
            "ZRACEhMKD1NVQl9DU19EaWNlSW5mbxADEhQKEFNVQl9TQ19UaHJvd0RpY2UQ",
            "BBIXChNTVUJfQ1NfT3BlcmF0ZVJvdXRlEAUSEwoPU1VCX1NDX0RpY2VJbmZv",
            "EAYSFQoRU1VCX1NDX0dhbWVSZXN1bHQQB2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LudoQuick.EMsgIDLudoQuick), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.RouteInfo), global::LudoQuick.RouteInfo.Parser, new[]{ "ChessId", "GoldBag", "Pos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.UserInfo), global::LudoQuick.UserInfo.Parser, new[]{ "ChairId", "RouteInfo", "FinishLineSwitch" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.ChessGrid), global::LudoQuick.ChessGrid.Parser, new[]{ "PosId", "SafeHouse", "GoldBag", "Prop", "Switch", "Inflection", "NextPos1", "NextPos2", "StartPoint", "EndPoint" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.MsgSceneInfoResp), global::LudoQuick.MsgSceneInfoResp.Parser, new[]{ "GameState", "TimeRemaining", "UserInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.MsgStartDiceResp), global::LudoQuick.MsgStartDiceResp.Parser, new[]{ "ChairId", "Times" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.MsgThrowDiceResp), global::LudoQuick.MsgThrowDiceResp.Parser, new[]{ "ChairId", "DiceRoll" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.MsgOperateRoute), global::LudoQuick.MsgOperateRoute.Parser, new[]{ "ChairId", "ChessId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.MsgDiceInfoResp), global::LudoQuick.MsgDiceInfoResp.Parser, new[]{ "ChairId", "ChessId", "RouteNum", "PropId", "Code" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.GameResult), global::LudoQuick.GameResult.Parser, new[]{ "ChairId", "UserInfo", "UserGold", "Win", "Bet" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LudoQuick.MsgResultResp), global::LudoQuick.MsgResultResp.Parser, new[]{ "Result" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///消息号
  /// </summary>
  public enum EMsgIDLudoQuick {
    /// <summary>
    ///场景（流程需要前端不管）
    /// </summary>
    [pbr::OriginalName("MsgID_FirstPublish")] MsgIdFirstPublish = 0,
    /// <summary>
    ///随机首发(MsgCommonN32)0红1绿2黄3蓝
    /// </summary>
    [pbr::OriginalName("SUB_SC_FirstPublish")] SubScFirstPublish = 1,
    /// <summary>
    ///开始投掷(MsgStartDiceResp)
    /// </summary>
    [pbr::OriginalName("SUB_SC_StartDice")] SubScStartDice = 2,
    /// <summary>
    ///投掷骰子(MsgCommonBool)
    /// </summary>
    [pbr::OriginalName("SUB_CS_DiceInfo")] SubCsDiceInfo = 3,
    /// <summary>
    ///投掷结果(MsgThrowDiceResp)
    /// </summary>
    [pbr::OriginalName("SUB_SC_ThrowDice")] SubScThrowDice = 4,
    /// <summary>
    ///操作棋子(MsgOperateRoute)
    /// </summary>
    [pbr::OriginalName("SUB_CS_OperateRoute")] SubCsOperateRoute = 5,
    /// <summary>
    ///骰子结果(MsgDiceInfoResp)
    /// </summary>
    [pbr::OriginalName("SUB_SC_DiceInfo")] SubScDiceInfo = 6,
    /// <summary>
    ///游戏结果(MsgResultResp)
    /// </summary>
    [pbr::OriginalName("SUB_SC_GameResult")] SubScGameResult = 7,
  }

  #endregion

  #region Messages
  /// <summary>
  ///棋子信息
  /// </summary>
  public sealed partial class RouteInfo : pb::IMessage<RouteInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RouteInfo> _parser = new pb::MessageParser<RouteInfo>(() => new RouteInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RouteInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RouteInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RouteInfo(RouteInfo other) : this() {
      chessId_ = other.chessId_;
      goldBag_ = other.goldBag_;
      pos_ = other.pos_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RouteInfo Clone() {
      return new RouteInfo(this);
    }

    /// <summary>Field number for the "chess_id" field.</summary>
    public const int ChessIdFieldNumber = 1;
    private int chessId_;
    /// <summary>
    ///棋子信息0123
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChessId {
      get { return chessId_; }
      set {
        chessId_ = value;
      }
    }

    /// <summary>Field number for the "gold_bag" field.</summary>
    public const int GoldBagFieldNumber = 2;
    private int goldBag_;
    /// <summary>
    ///钱袋信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoldBag {
      get { return goldBag_; }
      set {
        goldBag_ = value;
      }
    }

    /// <summary>Field number for the "pos" field.</summary>
    public const int PosFieldNumber = 3;
    private int pos_;
    /// <summary>
    ///棋子位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Pos {
      get { return pos_; }
      set {
        pos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RouteInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RouteInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChessId != other.ChessId) return false;
      if (GoldBag != other.GoldBag) return false;
      if (Pos != other.Pos) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChessId != 0) hash ^= ChessId.GetHashCode();
      if (GoldBag != 0) hash ^= GoldBag.GetHashCode();
      if (Pos != 0) hash ^= Pos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChessId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChessId);
      }
      if (GoldBag != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoldBag);
      }
      if (Pos != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Pos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChessId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChessId);
      }
      if (GoldBag != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoldBag);
      }
      if (Pos != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Pos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChessId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChessId);
      }
      if (GoldBag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoldBag);
      }
      if (Pos != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pos);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RouteInfo other) {
      if (other == null) {
        return;
      }
      if (other.ChessId != 0) {
        ChessId = other.ChessId;
      }
      if (other.GoldBag != 0) {
        GoldBag = other.GoldBag;
      }
      if (other.Pos != 0) {
        Pos = other.Pos;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChessId = input.ReadInt32();
            break;
          }
          case 16: {
            GoldBag = input.ReadInt32();
            break;
          }
          case 24: {
            Pos = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChessId = input.ReadInt32();
            break;
          }
          case 16: {
            GoldBag = input.ReadInt32();
            break;
          }
          case 24: {
            Pos = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///用户信息
  /// </summary>
  public sealed partial class UserInfo : pb::IMessage<UserInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserInfo> _parser = new pb::MessageParser<UserInfo>(() => new UserInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo(UserInfo other) : this() {
      chairId_ = other.chairId_;
      routeInfo_ = other.routeInfo_.Clone();
      finishLineSwitch_ = other.finishLineSwitch_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo Clone() {
      return new UserInfo(this);
    }

    /// <summary>Field number for the "chair_id" field.</summary>
    public const int ChairIdFieldNumber = 1;
    private int chairId_;
    /// <summary>
    ///椅子号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChairId {
      get { return chairId_; }
      set {
        chairId_ = value;
      }
    }

    /// <summary>Field number for the "route_info" field.</summary>
    public const int RouteInfoFieldNumber = 2;
    private static readonly pb::FieldCodec<global::LudoQuick.RouteInfo> _repeated_routeInfo_codec
        = pb::FieldCodec.ForMessage(18, global::LudoQuick.RouteInfo.Parser);
    private readonly pbc::RepeatedField<global::LudoQuick.RouteInfo> routeInfo_ = new pbc::RepeatedField<global::LudoQuick.RouteInfo>();
    /// <summary>
    ///棋子信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LudoQuick.RouteInfo> RouteInfo {
      get { return routeInfo_; }
    }

    /// <summary>Field number for the "finish_line_switch" field.</summary>
    public const int FinishLineSwitchFieldNumber = 3;
    private bool finishLineSwitch_;
    /// <summary>
    ///终点线开关
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool FinishLineSwitch {
      get { return finishLineSwitch_; }
      set {
        finishLineSwitch_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChairId != other.ChairId) return false;
      if(!routeInfo_.Equals(other.routeInfo_)) return false;
      if (FinishLineSwitch != other.FinishLineSwitch) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChairId != 0) hash ^= ChairId.GetHashCode();
      hash ^= routeInfo_.GetHashCode();
      if (FinishLineSwitch != false) hash ^= FinishLineSwitch.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      routeInfo_.WriteTo(output, _repeated_routeInfo_codec);
      if (FinishLineSwitch != false) {
        output.WriteRawTag(24);
        output.WriteBool(FinishLineSwitch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      routeInfo_.WriteTo(ref output, _repeated_routeInfo_codec);
      if (FinishLineSwitch != false) {
        output.WriteRawTag(24);
        output.WriteBool(FinishLineSwitch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChairId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChairId);
      }
      size += routeInfo_.CalculateSize(_repeated_routeInfo_codec);
      if (FinishLineSwitch != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserInfo other) {
      if (other == null) {
        return;
      }
      if (other.ChairId != 0) {
        ChairId = other.ChairId;
      }
      routeInfo_.Add(other.routeInfo_);
      if (other.FinishLineSwitch != false) {
        FinishLineSwitch = other.FinishLineSwitch;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 18: {
            routeInfo_.AddEntriesFrom(input, _repeated_routeInfo_codec);
            break;
          }
          case 24: {
            FinishLineSwitch = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 18: {
            routeInfo_.AddEntriesFrom(ref input, _repeated_routeInfo_codec);
            break;
          }
          case 24: {
            FinishLineSwitch = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///棋格信息
  /// </summary>
  public sealed partial class ChessGrid : pb::IMessage<ChessGrid>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChessGrid> _parser = new pb::MessageParser<ChessGrid>(() => new ChessGrid());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChessGrid> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChessGrid() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChessGrid(ChessGrid other) : this() {
      posId_ = other.posId_;
      safeHouse_ = other.safeHouse_;
      goldBag_ = other.goldBag_;
      prop_ = other.prop_;
      switch_ = other.switch_;
      inflection_ = other.inflection_;
      nextPos1_ = other.nextPos1_;
      nextPos2_ = other.nextPos2_;
      startPoint_ = other.startPoint_;
      endPoint_ = other.endPoint_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChessGrid Clone() {
      return new ChessGrid(this);
    }

    /// <summary>Field number for the "pos_id" field.</summary>
    public const int PosIdFieldNumber = 1;
    private int posId_;
    /// <summary>
    ///格子id 1-76 红
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PosId {
      get { return posId_; }
      set {
        posId_ = value;
      }
    }

    /// <summary>Field number for the "safe_house" field.</summary>
    public const int SafeHouseFieldNumber = 2;
    private int safeHouse_;
    /// <summary>
    ///安全屋1是0不是
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SafeHouse {
      get { return safeHouse_; }
      set {
        safeHouse_ = value;
      }
    }

    /// <summary>Field number for the "gold_bag" field.</summary>
    public const int GoldBagFieldNumber = 3;
    private int goldBag_;
    /// <summary>
    ///是否有钱袋
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoldBag {
      get { return goldBag_; }
      set {
        goldBag_ = value;
      }
    }

    /// <summary>Field number for the "prop" field.</summary>
    public const int PropFieldNumber = 4;
    private int prop_;
    /// <summary>
    ///道具格子
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Prop {
      get { return prop_; }
      set {
        prop_ = value;
      }
    }

    /// <summary>Field number for the "switch" field.</summary>
    public const int SwitchFieldNumber = 5;
    private int switch_;
    /// <summary>
    ///开关
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Switch {
      get { return switch_; }
      set {
        switch_ = value;
      }
    }

    /// <summary>Field number for the "inflection" field.</summary>
    public const int InflectionFieldNumber = 6;
    private int inflection_;
    /// <summary>
    ///拐点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Inflection {
      get { return inflection_; }
      set {
        inflection_ = value;
      }
    }

    /// <summary>Field number for the "next_pos1" field.</summary>
    public const int NextPos1FieldNumber = 7;
    private int nextPos1_;
    /// <summary>
    ///常规拐点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NextPos1 {
      get { return nextPos1_; }
      set {
        nextPos1_ = value;
      }
    }

    /// <summary>Field number for the "next_pos2" field.</summary>
    public const int NextPos2FieldNumber = 8;
    private int nextPos2_;
    /// <summary>
    ///终点拐点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NextPos2 {
      get { return nextPos2_; }
      set {
        nextPos2_ = value;
      }
    }

    /// <summary>Field number for the "start_point" field.</summary>
    public const int StartPointFieldNumber = 9;
    private int startPoint_;
    /// <summary>
    ///起点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartPoint {
      get { return startPoint_; }
      set {
        startPoint_ = value;
      }
    }

    /// <summary>Field number for the "end_point" field.</summary>
    public const int EndPointFieldNumber = 10;
    private int endPoint_;
    /// <summary>
    ///终点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EndPoint {
      get { return endPoint_; }
      set {
        endPoint_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChessGrid);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChessGrid other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PosId != other.PosId) return false;
      if (SafeHouse != other.SafeHouse) return false;
      if (GoldBag != other.GoldBag) return false;
      if (Prop != other.Prop) return false;
      if (Switch != other.Switch) return false;
      if (Inflection != other.Inflection) return false;
      if (NextPos1 != other.NextPos1) return false;
      if (NextPos2 != other.NextPos2) return false;
      if (StartPoint != other.StartPoint) return false;
      if (EndPoint != other.EndPoint) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PosId != 0) hash ^= PosId.GetHashCode();
      if (SafeHouse != 0) hash ^= SafeHouse.GetHashCode();
      if (GoldBag != 0) hash ^= GoldBag.GetHashCode();
      if (Prop != 0) hash ^= Prop.GetHashCode();
      if (Switch != 0) hash ^= Switch.GetHashCode();
      if (Inflection != 0) hash ^= Inflection.GetHashCode();
      if (NextPos1 != 0) hash ^= NextPos1.GetHashCode();
      if (NextPos2 != 0) hash ^= NextPos2.GetHashCode();
      if (StartPoint != 0) hash ^= StartPoint.GetHashCode();
      if (EndPoint != 0) hash ^= EndPoint.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PosId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PosId);
      }
      if (SafeHouse != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SafeHouse);
      }
      if (GoldBag != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GoldBag);
      }
      if (Prop != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Prop);
      }
      if (Switch != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Switch);
      }
      if (Inflection != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Inflection);
      }
      if (NextPos1 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(NextPos1);
      }
      if (NextPos2 != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(NextPos2);
      }
      if (StartPoint != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(StartPoint);
      }
      if (EndPoint != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(EndPoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PosId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(PosId);
      }
      if (SafeHouse != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SafeHouse);
      }
      if (GoldBag != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GoldBag);
      }
      if (Prop != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Prop);
      }
      if (Switch != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Switch);
      }
      if (Inflection != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Inflection);
      }
      if (NextPos1 != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(NextPos1);
      }
      if (NextPos2 != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(NextPos2);
      }
      if (StartPoint != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(StartPoint);
      }
      if (EndPoint != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(EndPoint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PosId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosId);
      }
      if (SafeHouse != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SafeHouse);
      }
      if (GoldBag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoldBag);
      }
      if (Prop != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Prop);
      }
      if (Switch != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Switch);
      }
      if (Inflection != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Inflection);
      }
      if (NextPos1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NextPos1);
      }
      if (NextPos2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NextPos2);
      }
      if (StartPoint != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartPoint);
      }
      if (EndPoint != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EndPoint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChessGrid other) {
      if (other == null) {
        return;
      }
      if (other.PosId != 0) {
        PosId = other.PosId;
      }
      if (other.SafeHouse != 0) {
        SafeHouse = other.SafeHouse;
      }
      if (other.GoldBag != 0) {
        GoldBag = other.GoldBag;
      }
      if (other.Prop != 0) {
        Prop = other.Prop;
      }
      if (other.Switch != 0) {
        Switch = other.Switch;
      }
      if (other.Inflection != 0) {
        Inflection = other.Inflection;
      }
      if (other.NextPos1 != 0) {
        NextPos1 = other.NextPos1;
      }
      if (other.NextPos2 != 0) {
        NextPos2 = other.NextPos2;
      }
      if (other.StartPoint != 0) {
        StartPoint = other.StartPoint;
      }
      if (other.EndPoint != 0) {
        EndPoint = other.EndPoint;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PosId = input.ReadInt32();
            break;
          }
          case 16: {
            SafeHouse = input.ReadInt32();
            break;
          }
          case 24: {
            GoldBag = input.ReadInt32();
            break;
          }
          case 32: {
            Prop = input.ReadInt32();
            break;
          }
          case 40: {
            Switch = input.ReadInt32();
            break;
          }
          case 48: {
            Inflection = input.ReadInt32();
            break;
          }
          case 56: {
            NextPos1 = input.ReadInt32();
            break;
          }
          case 64: {
            NextPos2 = input.ReadInt32();
            break;
          }
          case 72: {
            StartPoint = input.ReadInt32();
            break;
          }
          case 80: {
            EndPoint = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PosId = input.ReadInt32();
            break;
          }
          case 16: {
            SafeHouse = input.ReadInt32();
            break;
          }
          case 24: {
            GoldBag = input.ReadInt32();
            break;
          }
          case 32: {
            Prop = input.ReadInt32();
            break;
          }
          case 40: {
            Switch = input.ReadInt32();
            break;
          }
          case 48: {
            Inflection = input.ReadInt32();
            break;
          }
          case 56: {
            NextPos1 = input.ReadInt32();
            break;
          }
          case 64: {
            NextPos2 = input.ReadInt32();
            break;
          }
          case 72: {
            StartPoint = input.ReadInt32();
            break;
          }
          case 80: {
            EndPoint = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///场景消息
  /// </summary>
  public sealed partial class MsgSceneInfoResp : pb::IMessage<MsgSceneInfoResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgSceneInfoResp> _parser = new pb::MessageParser<MsgSceneInfoResp>(() => new MsgSceneInfoResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgSceneInfoResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgSceneInfoResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgSceneInfoResp(MsgSceneInfoResp other) : this() {
      gameState_ = other.gameState_;
      timeRemaining_ = other.timeRemaining_;
      userInfo_ = other.userInfo_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgSceneInfoResp Clone() {
      return new MsgSceneInfoResp(this);
    }

    /// <summary>Field number for the "game_state" field.</summary>
    public const int GameStateFieldNumber = 1;
    private int gameState_;
    /// <summary>
    ///游戏状态 0：选场 非零：对应椅子操作中
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GameState {
      get { return gameState_; }
      set {
        gameState_ = value;
      }
    }

    /// <summary>Field number for the "time_remaining" field.</summary>
    public const int TimeRemainingFieldNumber = 2;
    private int timeRemaining_;
    /// <summary>
    ///剩余时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TimeRemaining {
      get { return timeRemaining_; }
      set {
        timeRemaining_ = value;
      }
    }

    /// <summary>Field number for the "user_info" field.</summary>
    public const int UserInfoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::LudoQuick.UserInfo> _repeated_userInfo_codec
        = pb::FieldCodec.ForMessage(26, global::LudoQuick.UserInfo.Parser);
    private readonly pbc::RepeatedField<global::LudoQuick.UserInfo> userInfo_ = new pbc::RepeatedField<global::LudoQuick.UserInfo>();
    /// <summary>
    ///用户信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LudoQuick.UserInfo> UserInfo {
      get { return userInfo_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgSceneInfoResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgSceneInfoResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameState != other.GameState) return false;
      if (TimeRemaining != other.TimeRemaining) return false;
      if(!userInfo_.Equals(other.userInfo_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GameState != 0) hash ^= GameState.GetHashCode();
      if (TimeRemaining != 0) hash ^= TimeRemaining.GetHashCode();
      hash ^= userInfo_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameState != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameState);
      }
      if (TimeRemaining != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TimeRemaining);
      }
      userInfo_.WriteTo(output, _repeated_userInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameState != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GameState);
      }
      if (TimeRemaining != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TimeRemaining);
      }
      userInfo_.WriteTo(ref output, _repeated_userInfo_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GameState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameState);
      }
      if (TimeRemaining != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TimeRemaining);
      }
      size += userInfo_.CalculateSize(_repeated_userInfo_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgSceneInfoResp other) {
      if (other == null) {
        return;
      }
      if (other.GameState != 0) {
        GameState = other.GameState;
      }
      if (other.TimeRemaining != 0) {
        TimeRemaining = other.TimeRemaining;
      }
      userInfo_.Add(other.userInfo_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameState = input.ReadInt32();
            break;
          }
          case 16: {
            TimeRemaining = input.ReadInt32();
            break;
          }
          case 26: {
            userInfo_.AddEntriesFrom(input, _repeated_userInfo_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameState = input.ReadInt32();
            break;
          }
          case 16: {
            TimeRemaining = input.ReadInt32();
            break;
          }
          case 26: {
            userInfo_.AddEntriesFrom(ref input, _repeated_userInfo_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///开始投掷
  /// </summary>
  public sealed partial class MsgStartDiceResp : pb::IMessage<MsgStartDiceResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgStartDiceResp> _parser = new pb::MessageParser<MsgStartDiceResp>(() => new MsgStartDiceResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgStartDiceResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgStartDiceResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgStartDiceResp(MsgStartDiceResp other) : this() {
      chairId_ = other.chairId_;
      times_ = other.times_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgStartDiceResp Clone() {
      return new MsgStartDiceResp(this);
    }

    /// <summary>Field number for the "chair_id" field.</summary>
    public const int ChairIdFieldNumber = 1;
    private int chairId_;
    /// <summary>
    ///椅子号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChairId {
      get { return chairId_; }
      set {
        chairId_ = value;
      }
    }

    /// <summary>Field number for the "times" field.</summary>
    public const int TimesFieldNumber = 2;
    private int times_;
    /// <summary>
    ///剩余时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Times {
      get { return times_; }
      set {
        times_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgStartDiceResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgStartDiceResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChairId != other.ChairId) return false;
      if (Times != other.Times) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChairId != 0) hash ^= ChairId.GetHashCode();
      if (Times != 0) hash ^= Times.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (Times != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Times);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (Times != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Times);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChairId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChairId);
      }
      if (Times != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Times);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgStartDiceResp other) {
      if (other == null) {
        return;
      }
      if (other.ChairId != 0) {
        ChairId = other.ChairId;
      }
      if (other.Times != 0) {
        Times = other.Times;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            Times = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            Times = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///投掷结果
  /// </summary>
  public sealed partial class MsgThrowDiceResp : pb::IMessage<MsgThrowDiceResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgThrowDiceResp> _parser = new pb::MessageParser<MsgThrowDiceResp>(() => new MsgThrowDiceResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgThrowDiceResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgThrowDiceResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgThrowDiceResp(MsgThrowDiceResp other) : this() {
      chairId_ = other.chairId_;
      diceRoll_ = other.diceRoll_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgThrowDiceResp Clone() {
      return new MsgThrowDiceResp(this);
    }

    /// <summary>Field number for the "chair_id" field.</summary>
    public const int ChairIdFieldNumber = 1;
    private int chairId_;
    /// <summary>
    ///椅子号 对应颜色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChairId {
      get { return chairId_; }
      set {
        chairId_ = value;
      }
    }

    /// <summary>Field number for the "dice_roll" field.</summary>
    public const int DiceRollFieldNumber = 2;
    private int diceRoll_;
    /// <summary>
    ///骰子点数	
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DiceRoll {
      get { return diceRoll_; }
      set {
        diceRoll_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgThrowDiceResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgThrowDiceResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChairId != other.ChairId) return false;
      if (DiceRoll != other.DiceRoll) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChairId != 0) hash ^= ChairId.GetHashCode();
      if (DiceRoll != 0) hash ^= DiceRoll.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (DiceRoll != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DiceRoll);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (DiceRoll != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DiceRoll);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChairId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChairId);
      }
      if (DiceRoll != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DiceRoll);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgThrowDiceResp other) {
      if (other == null) {
        return;
      }
      if (other.ChairId != 0) {
        ChairId = other.ChairId;
      }
      if (other.DiceRoll != 0) {
        DiceRoll = other.DiceRoll;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            DiceRoll = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            DiceRoll = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///操作棋子
  /// </summary>
  public sealed partial class MsgOperateRoute : pb::IMessage<MsgOperateRoute>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgOperateRoute> _parser = new pb::MessageParser<MsgOperateRoute>(() => new MsgOperateRoute());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgOperateRoute> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOperateRoute() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOperateRoute(MsgOperateRoute other) : this() {
      chairId_ = other.chairId_;
      chessId_ = other.chessId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgOperateRoute Clone() {
      return new MsgOperateRoute(this);
    }

    /// <summary>Field number for the "chair_id" field.</summary>
    public const int ChairIdFieldNumber = 1;
    private int chairId_;
    /// <summary>
    ///椅子号 对应颜色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChairId {
      get { return chairId_; }
      set {
        chairId_ = value;
      }
    }

    /// <summary>Field number for the "chess_id" field.</summary>
    public const int ChessIdFieldNumber = 2;
    private int chessId_;
    /// <summary>
    ///棋子ID 0123
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChessId {
      get { return chessId_; }
      set {
        chessId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgOperateRoute);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgOperateRoute other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChairId != other.ChairId) return false;
      if (ChessId != other.ChessId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChairId != 0) hash ^= ChairId.GetHashCode();
      if (ChessId != 0) hash ^= ChessId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (ChessId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChessId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (ChessId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChessId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChairId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChairId);
      }
      if (ChessId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChessId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgOperateRoute other) {
      if (other == null) {
        return;
      }
      if (other.ChairId != 0) {
        ChairId = other.ChairId;
      }
      if (other.ChessId != 0) {
        ChessId = other.ChessId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            ChessId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            ChessId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///骰子数据
  /// </summary>
  public sealed partial class MsgDiceInfoResp : pb::IMessage<MsgDiceInfoResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgDiceInfoResp> _parser = new pb::MessageParser<MsgDiceInfoResp>(() => new MsgDiceInfoResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgDiceInfoResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgDiceInfoResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgDiceInfoResp(MsgDiceInfoResp other) : this() {
      chairId_ = other.chairId_;
      chessId_ = other.chessId_;
      routeNum_ = other.routeNum_;
      propId_ = other.propId_;
      code_ = other.code_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgDiceInfoResp Clone() {
      return new MsgDiceInfoResp(this);
    }

    /// <summary>Field number for the "chair_id" field.</summary>
    public const int ChairIdFieldNumber = 1;
    private int chairId_;
    /// <summary>
    ///椅子号 对应颜色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChairId {
      get { return chairId_; }
      set {
        chairId_ = value;
      }
    }

    /// <summary>Field number for the "chess_id" field.</summary>
    public const int ChessIdFieldNumber = 2;
    private int chessId_;
    /// <summary>
    ///棋子ID 0123
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChessId {
      get { return chessId_; }
      set {
        chessId_ = value;
      }
    }

    /// <summary>Field number for the "route_num" field.</summary>
    public const int RouteNumFieldNumber = 3;
    private int routeNum_;
    /// <summary>
    ///走了多少格
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RouteNum {
      get { return routeNum_; }
      set {
        routeNum_ = value;
      }
    }

    /// <summary>Field number for the "prop_id" field.</summary>
    public const int PropIdFieldNumber = 4;
    private int propId_;
    /// <summary>
    ///道具类型 0：未触发 1：前进一格 2：前进三格 3：前进五格 4：前进七格 5：移动到最近棋子 6：移动到最近得安全屋 7 ：获得骰子 8：获得指定骰子 9：解除开关 10：解锁棋子
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PropId {
      get { return propId_; }
      set {
        propId_ = value;
      }
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 5;
    private int code_;
    /// <summary>
    ///对语言id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgDiceInfoResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgDiceInfoResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChairId != other.ChairId) return false;
      if (ChessId != other.ChessId) return false;
      if (RouteNum != other.RouteNum) return false;
      if (PropId != other.PropId) return false;
      if (Code != other.Code) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChairId != 0) hash ^= ChairId.GetHashCode();
      if (ChessId != 0) hash ^= ChessId.GetHashCode();
      if (RouteNum != 0) hash ^= RouteNum.GetHashCode();
      if (PropId != 0) hash ^= PropId.GetHashCode();
      if (Code != 0) hash ^= Code.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (ChessId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChessId);
      }
      if (RouteNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RouteNum);
      }
      if (PropId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PropId);
      }
      if (Code != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Code);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (ChessId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChessId);
      }
      if (RouteNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RouteNum);
      }
      if (PropId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PropId);
      }
      if (Code != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Code);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChairId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChairId);
      }
      if (ChessId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChessId);
      }
      if (RouteNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RouteNum);
      }
      if (PropId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PropId);
      }
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgDiceInfoResp other) {
      if (other == null) {
        return;
      }
      if (other.ChairId != 0) {
        ChairId = other.ChairId;
      }
      if (other.ChessId != 0) {
        ChessId = other.ChessId;
      }
      if (other.RouteNum != 0) {
        RouteNum = other.RouteNum;
      }
      if (other.PropId != 0) {
        PropId = other.PropId;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            ChessId = input.ReadInt32();
            break;
          }
          case 24: {
            RouteNum = input.ReadInt32();
            break;
          }
          case 32: {
            PropId = input.ReadInt32();
            break;
          }
          case 40: {
            Code = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 16: {
            ChessId = input.ReadInt32();
            break;
          }
          case 24: {
            RouteNum = input.ReadInt32();
            break;
          }
          case 32: {
            PropId = input.ReadInt32();
            break;
          }
          case 40: {
            Code = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///结算信息
  /// </summary>
  public sealed partial class GameResult : pb::IMessage<GameResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameResult> _parser = new pb::MessageParser<GameResult>(() => new GameResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GameResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameResult(GameResult other) : this() {
      chairId_ = other.chairId_;
      userInfo_ = other.userInfo_ != null ? other.userInfo_.Clone() : null;
      userGold_ = other.userGold_;
      win_ = other.win_;
      bet_ = other.bet_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GameResult Clone() {
      return new GameResult(this);
    }

    /// <summary>Field number for the "chair_id" field.</summary>
    public const int ChairIdFieldNumber = 1;
    private int chairId_;
    /// <summary>
    ///椅子号 对应颜色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChairId {
      get { return chairId_; }
      set {
        chairId_ = value;
      }
    }

    /// <summary>Field number for the "user_info" field.</summary>
    public const int UserInfoFieldNumber = 2;
    private global::LudoQuick.UserInfo userInfo_;
    /// <summary>
    ///用户信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::LudoQuick.UserInfo UserInfo {
      get { return userInfo_; }
      set {
        userInfo_ = value;
      }
    }

    /// <summary>Field number for the "user_gold" field.</summary>
    public const int UserGoldFieldNumber = 3;
    private long userGold_;
    /// <summary>
    ///用户金币
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long UserGold {
      get { return userGold_; }
      set {
        userGold_ = value;
      }
    }

    /// <summary>Field number for the "win" field.</summary>
    public const int WinFieldNumber = 4;
    private long win_;
    /// <summary>
    ///本次获得
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Win {
      get { return win_; }
      set {
        win_ = value;
      }
    }

    /// <summary>Field number for the "bet" field.</summary>
    public const int BetFieldNumber = 5;
    private long bet_;
    /// <summary>
    ///消耗金币
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Bet {
      get { return bet_; }
      set {
        bet_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GameResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GameResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChairId != other.ChairId) return false;
      if (!object.Equals(UserInfo, other.UserInfo)) return false;
      if (UserGold != other.UserGold) return false;
      if (Win != other.Win) return false;
      if (Bet != other.Bet) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ChairId != 0) hash ^= ChairId.GetHashCode();
      if (userInfo_ != null) hash ^= UserInfo.GetHashCode();
      if (UserGold != 0L) hash ^= UserGold.GetHashCode();
      if (Win != 0L) hash ^= Win.GetHashCode();
      if (Bet != 0L) hash ^= Bet.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (userInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserInfo);
      }
      if (UserGold != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(UserGold);
      }
      if (Win != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Win);
      }
      if (Bet != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Bet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChairId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChairId);
      }
      if (userInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserInfo);
      }
      if (UserGold != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(UserGold);
      }
      if (Win != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Win);
      }
      if (Bet != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Bet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChairId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChairId);
      }
      if (userInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserInfo);
      }
      if (UserGold != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(UserGold);
      }
      if (Win != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Win);
      }
      if (Bet != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Bet);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GameResult other) {
      if (other == null) {
        return;
      }
      if (other.ChairId != 0) {
        ChairId = other.ChairId;
      }
      if (other.userInfo_ != null) {
        if (userInfo_ == null) {
          UserInfo = new global::LudoQuick.UserInfo();
        }
        UserInfo.MergeFrom(other.UserInfo);
      }
      if (other.UserGold != 0L) {
        UserGold = other.UserGold;
      }
      if (other.Win != 0L) {
        Win = other.Win;
      }
      if (other.Bet != 0L) {
        Bet = other.Bet;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 18: {
            if (userInfo_ == null) {
              UserInfo = new global::LudoQuick.UserInfo();
            }
            input.ReadMessage(UserInfo);
            break;
          }
          case 24: {
            UserGold = input.ReadInt64();
            break;
          }
          case 32: {
            Win = input.ReadInt64();
            break;
          }
          case 40: {
            Bet = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChairId = input.ReadInt32();
            break;
          }
          case 18: {
            if (userInfo_ == null) {
              UserInfo = new global::LudoQuick.UserInfo();
            }
            input.ReadMessage(UserInfo);
            break;
          }
          case 24: {
            UserGold = input.ReadInt64();
            break;
          }
          case 32: {
            Win = input.ReadInt64();
            break;
          }
          case 40: {
            Bet = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///游戏结算
  /// </summary>
  public sealed partial class MsgResultResp : pb::IMessage<MsgResultResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgResultResp> _parser = new pb::MessageParser<MsgResultResp>(() => new MsgResultResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgResultResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LudoQuick.LudoQuickReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgResultResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgResultResp(MsgResultResp other) : this() {
      result_ = other.result_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgResultResp Clone() {
      return new MsgResultResp(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private static readonly pb::FieldCodec<global::LudoQuick.GameResult> _repeated_result_codec
        = pb::FieldCodec.ForMessage(10, global::LudoQuick.GameResult.Parser);
    private readonly pbc::RepeatedField<global::LudoQuick.GameResult> result_ = new pbc::RepeatedField<global::LudoQuick.GameResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::LudoQuick.GameResult> Result {
      get { return result_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgResultResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgResultResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!result_.Equals(other.result_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= result_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      result_.WriteTo(output, _repeated_result_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      result_.WriteTo(ref output, _repeated_result_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += result_.CalculateSize(_repeated_result_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgResultResp other) {
      if (other == null) {
        return;
      }
      result_.Add(other.result_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            result_.AddEntriesFrom(input, _repeated_result_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            result_.AddEntriesFrom(ref input, _repeated_result_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
